[package]
name = "app"
version = "0.1.0"
description = "Lightweight offline photo manager"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.6.2", features = [ "macos-private-api", "protocol-asset"] }
tauri-plugin-log = "2"
tauri-plugin-fs = { version = "2.0.0", features = ["watch"] }
tauri-plugin-dialog = "2"
ffmpeg-sidecar = "2.0.0"
chrono = "0.4.41"
tauri-plugin-store = "2.3.0"
rayon = "1.10"
exif = { package = "kamadak-exif", version = "0.6" }
once_cell = "1.21.3"
tauri-plugin-process = "2"
tokio = { version = "1.47.0", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.98"
img_hash = "3.2.0"
image = { version = "0.23.14", default-features = false, features = ["jpeg", "png", "webp"] }
hex = "0.4.3"
sha2 = "0.10.9"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
